dependencies:
  - python=3.6.0
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - geatpy
    - seaborn
    - tensorflow
    - pyecharts
    - beautifulsoup4
    - requests